// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models.Database;

namespace TempleTours.Migrations
{
    [DbContext(typeof(TempleTourDbContext))]
    partial class TempleTourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TempleTours.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TourTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TempleTours.Models.TourParty", b =>
                {
                    b.Property<int>("TourPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourPartyId");

                    b.HasIndex("TourId");

                    b.ToTable("TourParty");
                });

            modelBuilder.Entity("TempleTours.Models.TourParty", b =>
                {
                    b.HasOne("TempleTours.Models.Tour", null)
                        .WithMany("Parties")
                        .HasForeignKey("TourId");
                });

            modelBuilder.Entity("TempleTours.Models.Tour", b =>
                {
                    b.Navigation("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
